<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gbpmKuP' shared service.

return $this->privates['.service_locator.gbpmKuP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.5aciI7K', 'get_ServiceLocator_5aciI7KService.php', true],
    'App\\Controller\\BlogController::form' => ['privates', '.service_locator.tUQnhFH', 'get_ServiceLocator_TUQnhFHService.php', true],
    'App\\Controller\\BlogController::index' => ['privates', '.service_locator.v3YQQmu', 'get_ServiceLocator_V3YQQmuService.php', true],
    'App\\Controller\\BlogController::show' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.QvREiyY', 'get_ServiceLocator_QvREiyYService.php', true],
    'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.5aciI7K', 'get_ServiceLocator_5aciI7KService.php', true],
    'App\\Controller\\BlogController:form' => ['privates', '.service_locator.tUQnhFH', 'get_ServiceLocator_TUQnhFHService.php', true],
    'App\\Controller\\BlogController:index' => ['privates', '.service_locator.v3YQQmu', 'get_ServiceLocator_V3YQQmuService.php', true],
    'App\\Controller\\BlogController:show' => ['privates', '.service_locator.NUP9Hmn', 'get_ServiceLocator_NUP9HmnService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.QvREiyY', 'get_ServiceLocator_QvREiyYService.php', true],
], [
    'App\\Controller\\BlogController::delete' => '?',
    'App\\Controller\\BlogController::form' => '?',
    'App\\Controller\\BlogController::index' => '?',
    'App\\Controller\\BlogController::show' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\BlogController:delete' => '?',
    'App\\Controller\\BlogController:form' => '?',
    'App\\Controller\\BlogController:index' => '?',
    'App\\Controller\\BlogController:show' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
