<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpmPPlC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpmPPlC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSpmPPlC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSpmPPlC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSpmPPlC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SpmPPlC',
    'container.build_id' => 'a90af54c',
    'container.build_time' => 1573952199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpmPPlC');
