<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHLgaXUE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHLgaXUE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHLgaXUE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHLgaXUE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHLgaXUE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HLgaXUE',
    'container.build_id' => '97861fde',
    'container.build_time' => 1573953892,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHLgaXUE');
