<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTwRmJ6n\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTwRmJ6n/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTwRmJ6n.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTwRmJ6n\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTwRmJ6n\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TwRmJ6n',
    'container.build_id' => '152c3289',
    'container.build_time' => 1573687306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTwRmJ6n');
