<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9wJYc4v' shared service.

return $this->privates['.service_locator.9wJYc4v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::categories' => ['privates', '.service_locator.5k.WQNz', 'get_ServiceLocator_5k_WQNzService.php', true],
    'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.5aciI7K', 'get_ServiceLocator_5aciI7KService.php', true],
    'App\\Controller\\BlogController::deleteCategory' => ['privates', '.service_locator.1d1_vaO', 'get_ServiceLocator_1d1VaOService.php', true],
    'App\\Controller\\BlogController::form' => ['privates', '.service_locator.tUQnhFH', 'get_ServiceLocator_TUQnhFHService.php', true],
    'App\\Controller\\BlogController::formCategory' => ['privates', '.service_locator.IKVNei_', 'get_ServiceLocator_IKVNeiService.php', true],
    'App\\Controller\\BlogController::index' => ['privates', '.service_locator.v3YQQmu', 'get_ServiceLocator_V3YQQmuService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.QvREiyY', 'get_ServiceLocator_QvREiyYService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true],
    'App\\Controller\\BlogController:categories' => ['privates', '.service_locator.5k.WQNz', 'get_ServiceLocator_5k_WQNzService.php', true],
    'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.5aciI7K', 'get_ServiceLocator_5aciI7KService.php', true],
    'App\\Controller\\BlogController:deleteCategory' => ['privates', '.service_locator.1d1_vaO', 'get_ServiceLocator_1d1VaOService.php', true],
    'App\\Controller\\BlogController:form' => ['privates', '.service_locator.tUQnhFH', 'get_ServiceLocator_TUQnhFHService.php', true],
    'App\\Controller\\BlogController:formCategory' => ['privates', '.service_locator.IKVNei_', 'get_ServiceLocator_IKVNeiService.php', true],
    'App\\Controller\\BlogController:index' => ['privates', '.service_locator.v3YQQmu', 'get_ServiceLocator_V3YQQmuService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.QvREiyY', 'get_ServiceLocator_QvREiyYService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true],
], [
    'App\\Controller\\BlogController::categories' => '?',
    'App\\Controller\\BlogController::delete' => '?',
    'App\\Controller\\BlogController::deleteCategory' => '?',
    'App\\Controller\\BlogController::form' => '?',
    'App\\Controller\\BlogController::formCategory' => '?',
    'App\\Controller\\BlogController::index' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\UserController::index' => '?',
    'App\\Controller\\BlogController:categories' => '?',
    'App\\Controller\\BlogController:delete' => '?',
    'App\\Controller\\BlogController:deleteCategory' => '?',
    'App\\Controller\\BlogController:form' => '?',
    'App\\Controller\\BlogController:formCategory' => '?',
    'App\\Controller\\BlogController:index' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
    'App\\Controller\\UserController:index' => '?',
]);
